### ISSUE TITLE
Why do we need a pair of reversals for causality?

### ISSUE THREAD

**Issue by alexkim** [JeremyCCHsu/vqvae-speech#1]
Hi Jeremy, thank you for making your VQ-VAE code publicly available. As I was looking through `models/vqvae.py`, I had a question about the `_encoder(self, x)` function. In the function, you call `x = tf.reverse(x, [1])` twice, and comment that this is necessary "to ensure causality."

By causality, are you referring to a causal filter (like in WaveNet)? If so, why is it necessary to reverse the time axis? Thanks!

**Comment by JeremyCCHsu** [comment]
The pair of `reverse` was there to ensure that no extra paddings were included during computation (I used `VALAD` padding. However, this is in fact not that important under normal situations where a natural utterance is used as the input. To sum up, I think it's fine to remove the pair of operations.

**Comment by alexkim** [comment]
I see, thanks!
