### ISSUE TITLE
trained embedding visualization

### ISSUE THREAD

**Issue by ghost** [JeremyCCHsu/vqvae-speech#7]
Hi Jeremy,
Nice results you've got! I was trying to reproduce as well, but couldn't get any good results. Could you share a screenshot of, or briefly describe, the 3D PCA of trained z embedding space? Just want to see what it should look like. What I got is basically centred on x and y axis. Thank you!

**Comment by JeremyCCHsu** [comment]
As far as I can recall, the shape of the distribution of the encodings was like a crescent moon or a hammer and the VQ centroids distributed inside it (the shape was not complicated but definitely not like a ball). Note that the encodings did not at all look like clusters; rather, it was more like what VQ is applied to a given distribution of data.

BTW, training is prone to fail, ending up with all encodings commits to the same centroid. I conjecture that this model could only be trained successfully trained with large batch size.
